[package]
name = "game_core9"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = "0.8.1"
downcast-rs = "2.0.2"
dyn-clone = "1.0.20"
rand = "0.9.2"
smallbox = "0.8.8"
thiserror = "2.0.17"

[[bench]]
name = "bench1"
harness = false