[package]
name = "arcanum_debugger3"
version = "0.1.0"
edition = "2024"

[dependencies]
game_core3 = { path = "../game_core3" }
eframe = { version = "0.29.1", default-features = true }
image = { version = "0.25", features = ["jpeg", "png"] } 
itertools = "0.14.0"
rand = "0.9.2"